function validate_time_grid(grid)
%VALIDATE_TIME_GRID 校验不依赖 double 绝对时间的样点网格。
arguments
    grid struct
end
required = {'gsc0','fraction0_ticks','step_num','step_den','count','fs_Hz', ...
    'f_gsc_Hz','epoch_id','clock_id','index0'};
assert(all(isfield(grid, required)), 'rtsim:time:IncompleteGrid', '时间网格字段不完整。');
assert(isa(grid.gsc0, 'uint64') && isa(grid.step_num, 'uint64') && ...
    isa(grid.step_den, 'uint64') && isa(grid.count, 'uint64') && isa(grid.index0, 'uint64'), ...
    'rtsim:time:UnsafeIntegerType', 'GSC、步长、计数和 index0 必须为 uint64。');
assert(grid.step_den > 0 && isfinite(grid.fraction0_ticks) && ...
    grid.fraction0_ticks >= 0 && grid.fraction0_ticks < 1, ...
    'rtsim:time:InvalidGrid', 'step_den 必须非零，fraction0_ticks 必须位于 [0,1)。');
assert(isscalar(grid.fs_Hz) && grid.fs_Hz > 0 && isfinite(grid.fs_Hz) && ...
    isscalar(grid.f_gsc_Hz) && grid.f_gsc_Hz > 0 && isfinite(grid.f_gsc_Hz), ...
    'rtsim:time:InvalidGrid', '采样率与 GSC 频率必须为有限正数。');
ratio = double(grid.step_num) / double(grid.step_den);
assert(abs(ratio - grid.f_gsc_Hz/grid.fs_Hz) <= 64*eps(max(1, ratio)), ...
    'rtsim:time:InconsistentRates', '有理步长与 fs_Hz、f_gsc_Hz 不一致。');
end
