function data = synthetic_metrology_inputs()
    % 所有数值均为声明的合成标准不确定度；不能替代校准证书或外场测量。

    names = ["power_standard", "cable_gain", "rx_gain_h", "rx_gain_v", "tx_gain_h", "tx_gain_v", ...
        "common_phase", "rx_phase_h", "rx_phase_v", "tx_phase_h", "tx_phase_v", ...
        "position", "attitude", "pattern_h", "pattern_v", "clock_time", "cable_delay", ...
        "frequency_standard", "oscillator", "power_estimator", "zdr_estimator", ...
        "phase_estimator", "delay_estimator", "frequency_estimator", "multipath", "temperature_gain"]';
    units = ["dB", "dB", "dB", "dB", "dB", "dB", "deg", "deg", "deg", "deg", "deg", ...
        "m", "deg", "dB", "dB", "ns", "ns", "Hz", "Hz", "dB", "dB", "deg", "ns", "Hz", "dB", "dB"]';
    u = [0.05 .025 .035 .035 .04 .04 .2 .15 .15 .18 .18 .02 .1 .05 .05 ...
        .03 .04 .05 .1 .025 .02 .1 .05 .08 .03 .02]';
    R = eye(numel(u));
    for pair = [3 4; 5 6; 8 9; 10 11; 14 15]'
        R(pair(1), pair(2)) = 0.8;
        R(pair(2), pair(1)) = 0.8;
    end

    data = struct('source_names', names, 'source_units', units, 'covariance', diag(u) * R * diag(u), ...
        'nominal_range_m', 1000, 'pattern_slope_db_per_deg', [0.05 0.03], ...
        'coverage_factor', 2, 'qualification', 'SYNTHETIC', 'seed', 7741);
    data.source_provenance = repmat("SYNTHETIC_DECLARED_STANDARD_UNCERTAINTY", numel(u), 1);
end
